kind: pipeline
type: docker
name: default

steps:
  - name: resource all in
    image: nas.mrcms.cn:8082/wuweiit/alpine:3.20.2
    pull: if-not-exists
    volumes:
      - name: joggle-admin-out
        path: /drone/admin
      - name: joggle-web-out
        path: /drone/web
    commands:
      - echo "copy admin manager web..."
      - scp -rp -o StrictHostKeyChecking=no /drone/admin/dist/* ./joggle-server/src/main/resources/static/manager/;
      - echo "copy web..."
      - scp -rp -o StrictHostKeyChecking=no /drone/web/* ./joggle-server/src/main/resources/static/;
      - echo "修改版本号 $DRONE_BUILD_BUMBER ";
      - sed -ie "s/dev-version/$DRONE_BUILD_BUMBER/g" ./joggle-server/src/main/resources/static/js/faceinner.ajax.js
    when:
      branch:
        - dev
        - test
        - release

  - name: build
    image: maven:3.8.6-jdk-8-slim
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
    volumes:
      - name: mavenRep
        path: /root/.m2
    commands:
      - echo 构建号：${DRONE_BRANCH}
      - echo "识别环境 决定资源"
      - if [ "${DRONE_BRANCH}" != "prod" ]; then echo 'prod' ;fi
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -U
      - mv joggle-server/target/joggle-server.jar joggle-server/target/app.jar
    branch:
      - dev
      - test
      - prod
      - release

  - name: scp to ${DRONE_BRANCH}
    image: appleboy/drone-scp
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
#    environment:
#      SSH_KEY_PATH: /root/.ssh/id_rsa
    volumes:
      - name: ssh
        path: /root/.ssh
    settings:
      host: 192.168.1.6
      username: root
      key:
        from_secret: ssh_rsa
      port: 22
      strip_components: 2
      target: /opt/data/joggle/
      source: joggle-server/target/app.jar
    when:
      branch:
        - test

  - name: scp to prod jar
    image: appleboy/drone-scp
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
    environment:
      SSH_KEY_PATH: /root/.ssh/id_rsa
    volumes:
      - name: ssh
        path: /root/.ssh
    settings:
      host: joggle.cn
      username: root
      keyPath: /root/.ssh/id_rsa
      port: 22
      strip_components: 2
      target: /opt/data/joggle/prod/
      source: joggle-server/target/app.jar
    when:
      branch:
        - prod

  - name: release docker image
    image: plugins/docker
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
    volumes:
      - name: dockerSock
        path: /var/run/docker.sock
    settings:
      insecure: false
      registry: nas.mrcms.cn:8083
      mirror: https://dkwe3jow.mirror.aliyuncs.com
      storage_path: /docker
      dockerfile: Dockerfile
      build_args: JAR=./joggle-server/target/app.jar
      username:
        from_secret: registry_nexus_username
      password:
        from_secret: registry_nexus_password
      repo: nas.mrcms.cn:8083/wuweiit/joggle-server
      tags:
        - ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - release

  - name: deploy-to-test
    pull: if-not-exists
    image: registry.cn-hangzhou.aliyuncs.com/sanchar/kubectl:v1.20.1
    extra_hosts:
      - lb.kubesphere.local:192.168.1.6
    volumes:
      - name: kube
        path: /root/.kube
    commands:
#      - kubectl --kubeconfig /root/.kube/config set image deployment/joggle *='nas.mrcms.cn:8082/wuweiit/joggle-server:${DRONE_BUILD_NUMBER}' -n home
      - kubectl --kubeconfig /root/.kube/config rollout restart deployment/joggle -n home
    when:
      branch:
        - test


#  - name: clean image
#    image: plugins/docker
#    pull: if-not-exists
#    volumes:
#      - name: dockerSock
#        path: /var/run/docker.sock
#    commands:
#      - if [ "${DRONE_BRANCH}" = "dev" ];then docker rmi -f $(docker image ls --filter=reference="192.168.1.6:32588/wuweiit/joggle-server:*" -q); fi
#      - if [ "${DRONE_BRANCH}" = "test" ];then docker rmi -f $(docker image ls --filter=reference="registry.cn-chengdu.aliyuncs.com/paazhi/${DRONE_REPO_NAME}:*" -q); fi
#      - if [ "${DRONE_BRANCH}" = "prod" ];then docker rmi -f $(docker image ls --filter=reference="registry.cn-chengdu.aliyuncs.com/panzhi/${DRONE_REPO_NAME}:*" -q); fi
#    when:
#      branch:
#        - dev
#        - test
#        - prod


volumes:
  - name: joggle-web-out
    host:
      path: /opt/build/joggle-web
  - name: joggle-admin-out
    host:
      path: /opt/build/joggle-admin
  - name: ssh
    host:
      path: /root/.ssh
  - name: kube
    host:
      path: /root/.kube
  - name: mavenRep
    host:
      path: /opt/data/drone/.m2
  - name: dockerSock
    host:
      path: /var/run/docker.sock
trigger:
  event:
    include:
      - push
      - custom
  branch:
    - prod
    - test
#    - dev
    - release