kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.8.6-jdk-8-slim
    volumes:
      - name: mavenRep
        path: /root/.m2
    commands:
      - echo ${DRONE_BRANCH}
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - name: image
    image: plugins/docker
    volumes:
      - name: dockerSock
        path: /var/run/docker.sock
    settings:
      mirror: https://dkwe3jow.mirror.aliyuncs.com
      storage_path: /docker
      build_args:
        JAR: joggle-server/target/joggle-server.jar
      username:
        from_secret: registry_hub_username
      password:
        from_secret: registry_hub_password
      repo: wuweiit/joggle-server
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
volumes:
  - name: mavenRep
    host:
      path: /opt/data/drone/.m2
  - name: dockerSock
    host:
      path: /var/run/docker.sock
