pipeline {
    agent any

   stages {
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-client deploying...."
                   sh '''
                       if [ "$BRANCH_NAME"  = "prod" ];then
                           echo "bullet-client uploading....."
                           scp ./bullet-client/target/bullet-client.jar root@192.168.1.6:/opt/bullet/lib/bullet-client.jar
                           echo "systemctl restart bullet ...."
                           ssh root@192.168.1.6 "systemctl restart bullet"
                       fi



                       if [ "$BRANCH_NAME"  = "build" ];then

                           cd ./build/client/

                            echo "从服务器下载linux Arm32版本的ngrok文件"
                            scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/ngrok/linux_arm/ngrok ./bin/ngrok
                            tar -zcvf bullet-client-linux_arm32.tar.gz ./*
                            scp -o StrictHostKeyChecking=no bullet-client-linux_arm32.tar.gz  root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/bullet/
                            rm -rf bullet-client-linux_arm32.tar.gz
                            rm -rf bin/ngrok


                           echo "从服务器下载linux版本的ngrok文件"
                           scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/ngrok/ngrok ./bin/ngrok
                           tar -zcvf bullet-client-linux_amd64.tar.gz ./*
                           scp -o StrictHostKeyChecking=no bullet-client-linux_amd64.tar.gz  root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/bullet/
                           rm -rf bullet-client-linux_amd64.tar.gz
                           rm -rf bin/ngrok

                           echo "从服务器下载Mac版本的ngrok文件"
                           scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/ngrok/darwin_amd64/ngrok ./bin/ngrok
                           tar -zcvf bullet-client-darwin.tar.gz ./*
                           scp -o StrictHostKeyChecking=no bullet-client-darwin.tar.gz  root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/bullet/


                           rm -rf bullet-client-darwin.tar.gz
                           rm -rf bin/ngrok


                           echo "从服务器下载Win版本的ngrokd文件"


                           scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/ngrok/windows_amd64/ngrok.exe ./bin/ngrok.exe
                           tar -zcvf bullet-client-windows.tar.gz ./*
                           scp -o StrictHostKeyChecking=no bullet-client-windows.tar.gz  root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/open.joggle.cn/bullet/

                           rm -rf bullet-client-windows.tar.gz
                           rm -rf bin/ngrok.exe
                       fi
                    '''

               }
           }
       }
}