pipeline {
    agent any

   stages {
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
                   sh "/opt/maven/bin/mvn clean package -Dmaven.test.skip=true"
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-client deploying...."
                   sh '''
                       echo "bullet-client uploading....."
                       scp ./bullet-client/target/bullet-client.jar root@192.168.1.100:/opt/bullet/lib/bullet-client.jar
                       echo "systemctl restart bullet ...."
                       ssh root@192.168.1.100 "systemctl restart bullet"
                    '''

               }
           }
       }
}