pipeline {
    agent any

   stages {
           stage('FixApiIP') {
                  steps {
                      echo "env: ${env.BRANCH_NAME}"
                      echo 'Deploying....'
                      sh '''

                         if [ "$BRANCH_NAME"  = "prod" ];then
                            sed -ie 's/http:\\/\\/localhost:8081//g' bullet-server/src/main/resources/static/js/faceinner.ajax.js
                         fi

                         # echo "修改版本号 $VERSION ";
                         # sed -ie "s/dev-version/$VERSION/g" static/lib/common.lib.js

                      '''
                  }
              }
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
                   sh "/opt/maven/bin/mvn clean package -Dmaven.test.skip=true"
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-server deploying...."
                   sh '''
                        echo "bullet-server uploading to tmp file ....."


                        if [ "$BRANCH_NAME"  = "prod" ];then

                            scp ./bullet-server/target/bullet-server.jar root@joggle.cn:/opt/data/springboot/prod/app.tmp.jar

                            echo "bullet-server restart ....."

                            ssh root@joggle.cn "cd /opt/data/springboot/prod/ && mv -f app.tmp.jar app.jar && docker restart springboot-prod"

                        fi

                        if [ "$BRANCH_NAME"  = "build" ];then
                            echo "正在转移jar文件"
                            mv ./bullet-server/target/bullet-server.jar ./build/server/lib/bullet-server.jar

                            cd ./build/server/
                            echo "从服务器下载对应的ngrokd文件"

                            scp root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/ngrok/ngrokd ./bin/ngrokd

                            tar -zcvf bullet-server.tar.gz ./*



                        fi
                    '''

               }
           }
       }
}