pipeline {
    agent any

   stages {
           stage('FixApiIP') {
                  steps {
                      echo "env: ${env.BRANCH_NAME}"
                      echo 'Deploying....'
                      sh '''

                         if [ "$BRANCH_NAME"  = "build" ];then
                            sed -ie 's/http:\\/\\/localhost:8081//g' bullet-server/src/main/resources/static/js/faceinner.ajax.js
                         fi

                         # echo "修改版本号 $VERSION ";
                         # sed -ie "s/dev-version/$VERSION/g" static/lib/common.lib.js

                      '''
                  }
              }
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
                   sh "/opt/maven/bin/mvn clean package -Dmaven.test.skip=true"
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-server deploying...."
                   sh '''
                        echo "bullet-server uploading to tmp file ....."


                        if [ "$BRANCH_NAME"  = "prod" ];then

                            scp -o StrictHostKeyChecking=no ./bullet-server/target/bullet-server.jar root@joggle.cn:/opt/data/springboot/prod/app.tmp.jar

                            echo "bullet-server restart ....."

                            ssh -o StrictHostKeyChecking=no root@joggle.cn "cd /opt/data/springboot/prod/ && mv -f app.tmp.jar app.jar && docker restart springboot-prod"

                            echo "发布前端页面"

                            sed -ie 's/localhost:8081//g' bullet-server/src/main/resources/static/js/faceinner.ajax.js

                            scp -r ./bullet-server/src/main/resources/static/* root@192.168.1.6:/opt/baota/docker-baota/www/wwwroot/www.joggle.cn/

                        fi

                        if [ "$BRANCH_NAME"  = "build" ];then
                            echo "正在转移jar文件"
                            mv ./bullet-server/target/bullet-server.jar ./build/server/lib/bullet-server.jar

                            cd ./build/server/

                            echo "从服务器下载linux版本的ngrokd文件"
                            scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/ngrok/ngrokd ./bin/ngrokd
                            tar -zcvf bullet-server-linux.tar.gz ./*
                            scp -o StrictHostKeyChecking=no bullet-server-linux.tar.gz  root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/bullet/

                            rm -rf bullet-server-linux.tar.gz
                            rm -rf bin/ngrokd

                            echo "从服务器下载Mac版本的ngrokd文件"
                            scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/ngrok/darwin_amd64/ngrokd ./bin/ngrokd
                            tar -zcvf bullet-server-darwin.tar.gz ./*
                            scp -o StrictHostKeyChecking=no bullet-server-darwin.tar.gz  root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/bullet/


                            rm -rf bullet-server-darwin.tar.gz
                            rm -rf bin/ngrokd


                            echo "从服务器下载Win版本的ngrokd文件"


                            scp -o StrictHostKeyChecking=no root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/ngrok/windows_amd64/ngrokd.exe ./bin/ngrokd.exe
                            tar -zcvf bullet-server-windows.tar.gz ./*
                            scp -o StrictHostKeyChecking=no bullet-server-windows.tar.gz  root@192.168.1.6:/opt/baota/wwwroot/open.joggle.cn/bullet/

                            rm -rf bullet-server-windows.tar.gz
                            rm -rf bin/ngrokd.exe




                        fi
                    '''

               }
           }
       }
}