pipeline {
    agent any

   stages {
           stage('FixApiIP') {
                  steps {
                      echo "env: ${env.BRANCH_NAME}"
                      echo 'Deploying....'
                      sh '''

                         if [ "$BRANCH_NAME"  = "prod" ];then
                            sed -ie 's/http:\\/\\/localhost:8081//g' Server/src/main/resources/static/js/faceinner.ajax.js
                         fi

                         # echo "修改版本号 $VERSION ";
                         # sed -ie "s/dev-version/$VERSION/g" static/lib/common.lib.js

                      '''
                  }
              }
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
                   sh "/opt/maven/bin/mvn clean package -Dmaven.test.skip=true"
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-server deploying...."
                   sh '''
                        ssh root@joggle.cn "docker stop springboot-prod"
                        echo "bullet-server uploading....."
                        scp ./Server/target/server-1.0-SNAPSHOT.jar root@joggle.cn:/opt/data/springboot/prod/app.jar
                        ssh root@joggle.cn "docker restart springboot-prod"
                    '''

               }
           }
       }
}