pipeline {
    agent any

   stages {
           stage('Build') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo "Building.."
                   sh "/opt/maven/bin/mvn clean package -Dmaven.test.skip=true"
               }
           }
           stage('Test') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"
                   echo 'Testing..'
               }
           }
           stage('Deploy') {
               steps {
                   echo "env: ${env.BRANCH_NAME}"

                   echo "bullet-server deploying...."
                   sh '''
                        echo "bullet-server uploading....."
                        scp ./Server/target/server-1.0-SNAPSHOT.war root@39.96.2.253:/opt/tomcat8/webapps/ROOT.war
                    '''

               }
           }
       }
}