
#
# Spring 配置
#
BULLET_MYSQL_HOST: 192.168.1.2
BULLET_MYSQL_PORT: 30118
BULLET_MYSQL_USERNAME: db_bullet
BULLET_MYSQL_PASSWORD: 123456
BULLET_MAIL_HOST: smtp.qiye.aliyun.com
BULLET_MAIL_PORT: 465
BULLET_MAIL_USERNAME: notice@joggle.cn
BULLET_MAIL_PASSWORD: 123456