
## 支付宝回调PC网站的URL地址 [默认]
ALIPAY_RETURN_URL: "/#/user/orders/pay/result"

## Swagger文档启用
SWAGGER_DOC_ENABLE: false

# 日志输出目录
LOGGING_PATH: logs/
#
# 服务器配置
#
server:
  port: ${SERVER_PORT:8081}



management:
  endpoints:
    web:
      basePath: ${spring.boot.admin.context-path}/actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#  server:
#    port: 8080
#
# Spring 配置
#

springfox:
  documentation:
    enabled: ${SWAGGER_DOC_ENABLE:true}
    swagger-ui:
      enabled: ${SWAGGER_DOC_ENABLE:true}
#      base-url: /api/v2/api-docs

knife4j:
  enable: ${SWAGGER_DOC_ENABLE:true}
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0

spring:
  session:
    store-type: redis
    timeout: 86400
  ## spring-boot-admin 配置
  boot:
    admin:
      ## admin 服务端访问地址
      context-path: /monitor
      ## admin 客户端连接服务端
      client:
        # 为了显示客户端的ip否则是以主机名显示的，这样需要添加hosts影射。
        instance:
          prefer-ip: true
        url: http://localhost:${server.port}/${spring.boot.admin.context-path}
#      instanceAuth:
#        defaultUserName: client_manager
#        defaultPassword: password
      instanceProxy:
        # 单体服务应用 确保能够传递jessionid
        ignored-headers:
          - "Set-Cookie"
          - "Authorization"
  profiles:
    active: dev
  application:
    name: joggle-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger3 需配置，不然展示不了列表
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
#    user:
#      name: admin     #
#      password: 123456 #
    oauth2:
      jwt:
        signingKey: ${JOGGLE_SIGNNING_KEY:123456}
      ignoreUrls:   /api/orders/alipay,/bootAdmin/**

  messages:
    basename: i18n/messages #相对路径 开头请勿添加斜杠

  thymeleaf:
    cache: false
  http:
    encoding:
      force: on
  devtools:
    restart:
      enabled: false
      # 需要实时更新的目录
      # additional-paths: src/main/java

  freemarker:
    templateLoaderPath: classpath:/static
    cache: false
    charset: UTF-8
    checkTemplateLocation: on
    contentType: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    requestContextAttribute: request
    suffix: .html
  # 邮件 配置
  mail:
    host: ${JOGGLE_MAIL_HOST:smtp.ym.163.com}
    port: ${JOGGLE_MAIL_PORT:994}
    username: ${JOGGLE_MAIL_USERNAME:notice@joggle.cn}
    password: ${JOGGLE_MAIL_PASSWORD:nopassword}
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 30000
      mail.smtp.writetimeout: 30000
      mail.smtp.ssl.socketFactory.class: com.wuweibi.bullet.mail.MailSSLSocketFactory
  # redis 配置
  redis:
    host: ${JOGGLE_REDIS_HOST:192.168.1.6}
    port: ${JOGGLE_REDIS_PORT:6379}
    password: ${JOGGLE_REDIS_PASSWORD:masterPass123.}
    lettuce:
      pool:
        maxTotal: 100
        maxWaitMillis : 100000
        max-idle: 10
  # 限流器配置
  rate-limiter:
    enabled: ${RATE_LIMITER_ENABLED:true}
    rate: 1000
    interval: 1000
    type: PER_CLIENT
    ignoreUrls:
      - /inner/**
      - /css/**
      - /js/**
      - /lib/**
      - /resource/**

  # 数据库配置
  datasource:
    driverClassName : com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${JOGGLE_MYSQL_HOST:bullet-server}:${JOGGLE_MYSQL_PORT:3306}/${JOGGLE_MYSQL_DATABASE:db_bullet}?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${JOGGLE_MYSQL_USERNAME:root}
    password: ${JOGGLE_MYSQL_PASSWORD:123456}
    initialSize: 20
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# mybatis-plus 配置信息
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*.xml,classpath*:/mapper/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wuweibi.bullet.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: false
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl




# log config
logging:
  config: 'classpath:logback-spring.xml'

# 设定ftl文件路径

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/api/open,/logout,/druid,/index.html,/js,/lib,/css,/resource,/view,/template,/manager

# joggle 配置
joggle:
  # ngrokd服务路径
  # ngrokd: ${JOGGLE_NGROKD_HOME:/opt/ngrok}
  # 前端访问地址
  serverUrl: ${JOGGLE_SERVER_URL:https://www.joggle.cn}
  # 调用接口的Token
  adminApiToken: ${JOGGLE_API_TOKEN:123456}
  aliAppcode: ${ALI_MARKET_APPCODE:xxxxx}
  alipay:
    appId: ${ALIPAY_MERCHANT_APPID:2021000121630337}
    privateKey: ${ALIPAY_MERCHANT_PRIVATE_KEY}
    alipayPublicKey: ${ALIPAY_PUBLIC_KEY}
    notifyUrl: ${ALIPAY_NOTIFY_URL:https://pay.joggle.cn/api/open/orders/alipay/callback}
    returnUrl: ${joggle.serverUrl}${ALIPAY_RETURN_URL}
  # oss 配置
  ali-oss:
    publicServerUrl: ${ALI_OSS_PUBLIC_URL:https://www.joggle.cn}
    accessKeyId: ${ALI_OSS_ACCESSKEY:xxx}
    accessKeySecret: ${ALI_OSS_KEYSECRET:xxx}
    publicBucketName: ${ALI_OSS_BUCKET:xxx}
  # ali sms 配置
  ali-sms:
    accessKeyId: ${ALI_SMS_ACCESSKEYID:LTAI5tAF7fUuz9xxxtd}
    accessKeySecret: ${ALI_SMS_KEYSECRET:xxxx}

# 微信配置（测试appid）
weixin:
  appId: wxc8e74d5165c333e6
  appSecret: a33692209929308c336b167ba226785a



