
## Swagger文档启用
SWAGGER_DOC_ENABLE: true
RATE_LIMITER_ENABLED: true

#
# Spring 配置
#
spring:
  devtools:
    restart:
      enabled: false
      # 表示从这个默认不触发重启的目录中除去static目录
      exclude: classpath:/static/**
      # additional-paths: classpath:/static

BULLET_SERVER_URL: "http://localhost:8081"

## 支付宝配置 [沙箱环境]
ALIPAY_MERCHANT_APPID: 2021000121630337
ALIPAY_MERCHANT_PRIVATE_KEY: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOAwr+awPpTMdosLZJPx5LoVnJJu3QDuoz/NkouWuWvw/Jvyj0ALJs1apwwVZbi1uht4tgCHToXtC6uUGMzBKER8V0dL0Cdqqa/yzKtjtTiDrGKOdXwDnkY1ZOUS1o/FTcFHiesEFFqxAdF4YhZ4u3+ZkMhQt02WW1ulnYhzHKU0G2wGdMYbBXDP628SbiYgwqdnkqCUtMY9PFoXD5dmGKAaKOKglzrOCM2GeshbFQIkeji6U0vuNrFRSxlg6zM62CnhZSVEFcHRVrIUkW8dNeh0fJ7jfExB165ya65b2fhNmfdd+lNYqu36npqiIr/gwxfqJxb8AepnaSE3tWmE/bAgMBAAECggEAJ5q3pS5pH9Y2wn6Nx62foE32QT/nEKAoNqlsUowrchYErCnwnOPY3rtT1jBFCjC6NEaAyx5wpCFVKs3hdweunk95xLmNwLMhbyp87meV8fzLD1p28iT8wDHn7t16wY2liN74qKDVAz3qt4JI+OXstDkassAj6sl6MQ0wY0+I1jipU/qkRr1ZdbyT63vqnsTUn1QQbo93HA3X0pNIXXbxFQhh4UIcxeqThCokaF7MvTPl2JbRxdzxvru0ICLOYRwydc+NMzo9cKWFH6gt6Mml50GCp1RyyzwUaA6z0iSdf/pkXwM3QhTv9QmikbfPRA0baHy6cUn4Ub0drEoJrPCYaQKBgQDJ31TDyO26tPHWCnJd/2oMQjGWn16n2LVIYbGIbDdwG0hjcqoZh7vWTL5SE6tVfgZg8hWAhwiXhhb63QFPTfzKE1mjbT5DPNQbImwmzv8w91u6Tb0T7noS3sLiaekVMuXKdvpYoZQn10LT4xrBAN0XzNFA983/PfAHDxpYPqQChwKBgQC0FtfWMsQIajuhlBynCXBTVC5PPRzwBOPB8MXVS81pTU+qWPmkCHfgUWs+uj3x0XSsvaNS4IStIiOyYRxouSX5cGNDalNDNGherm8M8wgRpTbCYGa6ULIBBwZrm3RO1Ezc92/bJeqAGj+D24a5QiaF27fUqnB4LFez4vNzbBMZDQKBgCl5EFkIto5dDjIDA2v8RTUvhDCFnVSuWM/+AhMc6GbHtB96Nyf3ksd8DL2f/NsbgQP5uCEnnMREcAQp01MPmpeJUikZEGmP3aOVdtKiRBszNk0YG3g0zi+CRFdvmssYIc1ulBARYfatarVNOvnby5BQK81FG7UMbHuGxsrKU7eRAoGAW9+TeQkpDQn1JfdDrsuX7Erz3STWUHSOJPDKXIhxYJk6XTNLGC3hyiR/S98Dnww2M7IDUlKMHS9feq8kKSDbiKeXXFsv4wcnf7YJnVeW9DmO+BbqEX79cJy+38LM0TJpjAkHnYt4WKYLZR9nWbevo3Z2EB5rhkNI8tKDVIz8KTkCgYEAxj31ffT3rb8c9TBl1uePyzBNo23mPkfHoWw1n5GP/kDnx7LdvEIlZFSfoUrcd0m8hMp10RDAY0jjAPOGAtqGGxZvaQPtrKA0bg5htGnMByfHK9z5L7efnk1O50RcFRhSirE170ymrl/nK0EaaIx8YBIVBfq2voH4Cy3ZcsNq4nE="
ALIPAY_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg0gjxN9/7SItPIgLQx+h0rUOw4ribQBJOdRdH1BK46ks1oQ6svlpEtXeLcc3W2bvjgps4FQFKoX3m4hyUXCSyKvhYDcb/s109mi+Cy4WQtTuF9c+F++JyI/whp1mUBx7v8Eif6aV5n4Hnsfsz2sCqADdo77QDTtUfJF6vxbm5GI7/fBGKEYG4p15DUFlc6U6KbYZJkY91w89t9WNO4IXr0GAa6AJcLUCoIr64CGOseIxWC1xjdRjBbRShDOver7yuj43Inu88zZ3W7LFm35dQEiSqBZTxgG5OQybD5zvy0HJL85HOYLkro4NmFbSeba7WFMreU0f36+cZboMSOPU6QIDAQAB"
ALIPAY_NOTIFY_URL: "https://pay.joggle.cn/api/open/orders/alipay/callback"
