
## Swagger文档启用
SWAGGER_DOC_ENABLE: true
RATE_LIMITER_ENABLED: true

#
# Spring 配置
#
spring:
  devtools:
    restart:
      enabled: false
      # 表示从这个默认不触发重启的目录中除去static目录
      exclude: classpath:/static/**
      # additional-paths: classpath:/static

JOGGLE_SERVER_URL: "https://pay.joggle.cn"

## 支付宝配置 [沙箱环境]
ALIPAY_MERCHANT_APPID: 9021000141609472
ALIPAY_MERCHANT_PRIVATE_KEY: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCQ6UVZQVK1OJwh9RU6YbVQuGnfsEykUHMJ6gDU5BuapA6j0P9AMc1A8O41AhBefsew2HA/G+JTjw7VJGnhJ0B9X2nk1oL//PDLlyf8w0J8r0UFpI8V/UzXWwUlaTxrUygCZ6ZgGAluiOj7B74tOgz0Foz/NftdhvdLcpC7AattgWWTxCNziPHUvPmUiuo+cjoqQuCHddnRRjml7Sko+F5WIU6VWstbIjuIJwgLH/CGyYm66r37yOAxMn4MjTxFwqkxo0JwKrbZXikdPAYV/tU0BudUZ2YJ0WDj/HwAGn9aeZ6oVy677H9q4yN11kLHUicW42riZ5idXya0V3BkLAv7AgMBAAECggEAVi1DfoboZrkZsOANFcERkMV6wPoZOgZVw2mTwQc+m0JBKo6ZnVWAmMQvBPsLPQbsPnEYn483kzWaPor/JFSxd12Mnfgrw4xqrshfkWOVYIzi4S4xoYQXdGK+trbUpYa4XmXBfZgN09w7oT3DjSXemjHm+8bgi4g9/HJPO8cMaXwK7jF7sGqh3QriJrx3JZBK/fsRxKGJcJ6jP7ybgRds5MvTlSlZnVrl5qLF6XO0c6hcn+QvV67dU0guWBabL2y9bOzAf+6koK57w5C8nSa4KVRSxBycO3HzJ9Ka5enD1EIb+RLTVHRvTOdK/tne76DQ4ks2WhzsEqvZSL4/OLhqsQKBgQDHtMjvQSvd6bnMDiY3I+Wg5yzfnzVKrwnEb+1fGawrmqc5/ow1JMTld1lha23vXg0rJTLtrT9dNOuB9FPgGTsbprj74bdvdBlizVMBUC24wzx+n5udDvInRAvgBWFrQvX5aKPp++H4Tu1MAd4U+q0iPvG6sh4AnENC25FQ9e9x1wKBgQC5wl3CFviNSuTqYmuY6I25jQiUR5d5CU08EAwknWTh86H2Nb62U93pnCSFoqqzdUruEKla3PrZyyX1+/JzlXR1lUC1HNWXnUOkVvLHOg6cF5ZmLltAaGFokIuAo1GCI9mqMZX/KxviIF7VOAG0YLMmozzrXKfgZERq+D1yL+d6fQKBgF4teVyrBT7fjAkY2xjByvZ4Tocek4kmxppmljB08OaXRilpS0F8l4YHJJV2jh+F4PvpzPyc6PbRkAZ27F8QRvmhRDc0mMbsn1Qis/Q4lXc+SvcD2eTVOYke4+K/ZtOofksh97rOWCA7SFjBwLNwC9nMiT6b5N4w0t9ioELn2AV9AoGAHIi5xD2pEnMltMdHheZ7FryOS9CveN0v6wEADIPM4lR9VYet8u3xEZh1l72EASsMRoNysE1vjxMAkseP16dmi0VQ+kEiojZ7FHxysJ2/bsTEyo9mXv9prxk9BJaRx67gGZ+iTd7+Wn7kclY3FNEh09aRXgoOk45zYAcf0TGAmjUCgYBI0wasycaAoTSvFqT3UzuO9QXr3ZTv8UktJ/canDRX/d2EfH0bGueAxq+ZrDBks/rpFOOt8I9yQwS3b3vbcXsZ9uK6BIq8jFd1kheqGw0kLuh87whkB+epdGxU17Tiuze4ngk+j2XBP1ro08FSvIXvlnWBdC13Q9nRBFRot9nvjQ=="
ALIPAY_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkFjTpaybOxE0iaxV/Sa3J4nDPtiHYxNxTiHzw8Jll/r23OWE7QQI9bLFelS30tYsKmZfxTNUKyVIaOYmR0zXFuG3W5HmttswMQkrU/0wzY/QCY3qVSomqylYdLhHcBvlgYdT8oHMzy69pabvRF+T7FGr8ffiSl+aIBY86B+w0g7LGU6gis9unMn/drGLrDaWV+xvU89ildhtvFTgZ+ZKp5Qw/lbce0xCCrdh6ifXVq0XqScpzok4DLlUeyXtFguWqWbbhgmVBrDicawuEdahQqCWr10/NvsiP+1kTF1gkvzNsmr5BIgaPwLuv/nDAEnhhPNNhm76kU8r90vp4MjFPwIDAQAB"
ALIPAY_NOTIFY_URL: "https://pay.joggle.cn/api/open/orders/alipay/callback"
